<div id="content-contact" class="content">

	<h1>Contact<br />
	&amp; Inquiries</h1>
	<p class="subheading">Get in touch</p>
	
	<div class="inner-content">
		<form action="/contact/inquire" id="contact-form" method="post">
			<fieldset>
				<input type="text" name="name" id="contact_name" placeholder="Name" value="" class="text requiredField small-text"/>
			</fieldset>
			<fieldset>
				<input type="text" name="phone" id="phone" placeholder="Phone" value="" class="text requiredField small-text"/>
			</fieldset>
			<fieldset>
				<input type="text" name="email" id="contact_email" placeholder="Email" value="" class="text requiredField email small-text"/>
			</fieldset>
			<fieldset>
				<textarea name="message" id="contact_message" placeholder="Message" rows="20" cols="30" class="text requiredField small-text"></textarea>
			</fieldset>
			<fieldset>
				<input name="contact_submit" id="contact_submit" value="" class="button blue" type="submit"/>
			</fieldset>
		</form><!--#contact_form-->
	</div>

	<div class="side-content" style="font-weight:400">
		<strong style="font-weight:600">New York City Camera Company Inc.</strong><br />
		<div class="black">
			400 West 14th St.<br />
			New York, NY 10014<br /><br />
			+ 1 732 895 5409<br />
			<a href="mailto:info@newyorkcitycamera.com" style="color:black">info@newyorkcitycamera.com</a><br />
			<br /><br /><br />
		</div>
		<div class="gray">
			<em>facebook</em><br />
			<a href="http://facebook.com/newyorkcitycamera" target="_blank">facebook.com/newyorkcitycamera</a><br />
			<br />
			<em>twitter</em><br />
			<a href="http://twitter.com/nycc" target="_blank">twitter.com/nycc</a>
		</div>
	</div>
	
	<div class="clear"></div>

</div><!-- #content-contact -->

<div class="clear"></div>

<script>
	$('#contact-form').submit( function(e){
		e.preventDefault();
		form_data = $(this).serialize();

		$.post('/contact/inquire', form_data, function(res){
			var msg = '';
			if( res.status.code == 200 ){
				alert('inquiry sent');
			}else{

				for( x in res.result.cause ){
					msg += res.result.cause[x] + '\n';
				}
				alert(msg);
			}
		});
	});
</script>
<script src="http://www.modernizr.com/downloads/modernizr-latest.js"></script>
<script>
/**
* HTML5 Placeholder Text, jQuery Fallback with Modernizr
*
* @url        http://uniquemethod.com/
* @author    Unique Method
*/
$(function()
{
    // check placeholder browser support
    if (!Modernizr.input.placeholder)
    {
    
        // set placeholder values
        $(this).find('[placeholder]').each(function()
        {
            if ($(this).val() == '') // if field is empty
            {
                $(this).val( $(this).attr('placeholder') );
            }
        });
        
        // focus and blur of placeholders
        $('[placeholder]').focus(function()
        {
            if ($(this).val() == $(this).attr('placeholder'))
            {
                $(this).val('');
                $(this).removeClass('placeholder');
            }
        }).blur(function()
        {
            if ($(this).val() == '' || $(this).val() == $(this).attr('placeholder'))
            {
                $(this).val($(this).attr('placeholder'));
                $(this).addClass('placeholder');
            }
        });
        
        // remove placeholders on submit
        $('[placeholder]').closest('form').submit(function()
        {
            $(this).find('[placeholder]').each(function()
            {
                if ($(this).val() == $(this).attr('placeholder'))
                {
                    $(this).val('');
                }
            })
        });
        
    }
});
</script>
