<div class="inner-content last">
	<form action="/contact/inquire" id="contact-form" method="post">
		<fieldset>
			<label>Name <span class="required">*</span></label>
			<input type="text" name="name" id="contact_name" value="" class="text requiredField"/>
		</fieldset>
		<fieldset>
			<label>Phone <span class="required">*</span></label>
			<input type="text" name="phone" id="phone" value="" class="text requiredField"/>
		</fieldset>
		<fieldset>
			<label>Email <span class="required">*</span></label>
			<input type="text" name="email" id="contact_email" value="" class="text requiredField email"/>
		</fieldset>
		<fieldset>
			<label>Your Message <span class="required">*</span></label>
			<textarea name="message" id="contact_message" rows="20" cols="30" class="text requiredField"></textarea>
		</fieldset>
		<fieldset>
			<input name="contact_submit" id="contact_submit" value="Send Message" class="button blue" type="submit"/>
		</fieldset>
	</form>
	<!--END form ID contact_form-->
</div>

<script>
	$('#contact-form').submit( function(e){
		e.preventDefault();
		form_data = $(this).serialize();

		$.post('/contact/inquire', form_data, function(res){
			var msg = '';
			if( res.status.code == 200 ){
				alert('inquiry sent');
			}else{

				for( x in res.result.cause ){
					msg += res.result.cause[x] + '\n';
				}
				alert(msg);
			}
		});
	});
</script>