<div id="content-company" class="content">

	<h1>NYCC</h1>
	<p class="subheading">We are New York City Camera Co.</p>
	
	<div class="column-left">
		<p>New York City Camera Company is a NYC based motion picture film and television equipment rental company. We offer domestic and international rentals, including managing and delivering camera and lens packages to global clients. In 2012 the company was founded by an industry IATSE 600 cinematographer. The company strives to deliver quality rentals at an affordable rate to professionals in the contemporary film industry.</p>
	</div>
	
	<div class="column-right">
		<p>We offer Cameras including the Arrifelx Digital System, ALEXA Plus + and Carl Zeiss Products including the Zeiss CP series Lenses. New York City Camera Company is determined to deliver exceptional customer service and a one-on-one client relationship. We are here to make your life easier on location.</p>
	</div>
	
	<div class="clear"></div>
	
	<p><em>Best,<br />
	Hunter</em></p>

</div><!-- #content-contact -->

<div class="clear"></div>
