<div id="content-equipment" class="content">

	<ul class="submenu">
		<li><a href="#" class="accessories"></a></li>
		<li><a href="#" class="lenses"></a></li>
		<li><a href="#" class="camera hit"></a></li>
	</ul>

	<div class="camera equip-content">
		<h1>Camera</h1>
		<p class="subheading">Equipment Rentals</p>

		<h2>ALEXA plus</h2>
		<p class="subheading">Camera</p>
	
		<div class="half-column">
			<p>1 Arri ALEXA Plus Digital Cinema Camera<br />
			1 Arri ALEXA EVF-1 Electronic Viewfinder<br />
			1 Arri ALEXA VMB-2 Viewfinder Mounting Bracket<br />
			1 Arri ALEXA Viewfinder Extension Bracket <br />
			1 Arri ALEXA Viewfinder Cable Short (0.35mm/1.2ft) KC 150-s<br />
			1 Arri ALEXA Viewfinder Cable Medium (0.65m/2.1ft) KC 151-S<br />
			1 Arri ALEXA Ethernet Cable (3.00m/9.8ft) KC 153-S<br />
			1 Arri XLR Sound Adapter Cable / 1 Mini Headphone Splitter<br />
			1 Arri ALEXA 12V Accessory Cable<br />
			1 Arri BPA-1 Bridge Plate Adapter for ALEXA<br />
			1 Arri WA-1 Wedge Adapter for ALEXA <br />
			1 Arri LB-1 Leveling Block for ALEXA<br />
			1 Arri SP-3 Shoulder Pad for ALEXA<br />
			1 Arri ALEXA SD Card, 4GB<br />
			1 Arri CCH-1 Center Camera Handle for ALEXA<br />
			1 Arri ALEXA PL Port Cap<br />
			1 Arri HEB-2 Handle Extension Block for ALEXA<br />
			1 Arri ALEXA Anton Bauer Battery Adapter Back for Gold Mount <br />
			4 Sony SxS Memory Cards 64 GB<br />
			1 Sony Card Reader 1 USB Cable<br />
			1 Arri BP-12 Bridge Plate Set (19mm)<br />
			1 12" Dovetail<br />
			2 Arri 19mm Support Rods Steel 13.6" 2 Chrosziel 15mm Support Rods Steel 12" <br />
			Arri High Speed License 120FPS / Arri Anamorphic De-Squeeze License</p>
			<h2>5D Mark III</h2>
			<p class="subheading">Camera</p>
	
			<p>1 Canon 5D Mark III Digital Camera <br />
			1  Canon EF 16-35mm II f/2.8 L-Series <br />
			1 Canon EF 24-105mm f/4.0 L-Series <br />
			4 Canon Batteries <br />
			3 SanDisk 32GB Extreme CF Cards 60MB/S<br />
			1 Canon Charger / 1 Canon AC Power Adapter</p>
		</div>
		<div class="half-column last">
			<p>1 TV Logic 5.6" - Full Version Multi-format HD/SD/HDM 3G Viewfinder Monitor</p>

			<p>1 TV Logic Panasonic Battery Mount, 2 Panasonic Batteries, and 1 Panasonic Charger</p>

			<p>1 TV Logic D-Tap Power Cable for the VFM-056WP Monitor<br />
			1 TV Logic External Protection Screen Panel for VFM-056W / 1 5.6" Hoodman <br />
			1 Cine Arm – Medium<br />
			1 12" BNC Cable / 1 BNC Male to BNC Female Adapter Right / 1 BNC Splitter <br />
			1 Anton Bauer Sandwich Adapter with 4 Powertap Connectors <br />
			1 Anton Bauer PowerTap Multi – 4 Female PowerTap Connectors</p>
		
			<h3>Batteries</h3>
			<p>4 Anton Bauer Hytron 140w 14.4Vv NiMH Battery<br />
			1 Anton Bauer TM4 4-Position Simultaneous Fast Charger<br />
			1 Arri 24V 10ft. 3-Pin Power Cable for ALEXA<br />
			1 Ari 221W/24v Power Supply</p>
		</div>
	
		<div class="clear"></div>
	
	</div><!-- .camera -->
	
	<div class="lenses equip-content">
		<h1>Lenses</h1>
		<p class="subheading">Available for Rent</p>
		<div class="half-column">
			<h2>Zeiss CP.2</h2>
			<p class="subheading">Lenses</p>
			<p>1 Zeiss Compact Prime Lenses (PL/EF Mount)<br />
			1 Zeiss Transport Case for CP.2 System / Torque Wrench / Siemens Test Chart<br />
			21mm – T2.9<br />
			28mm – T2.1<br />
			35mm – T2.1<br />
			50mm – T2.1<br />
			85mm – T2.1</p>
		</div>
		<div class="half-column last">
			<h2>LOMO Anamorphic</h2>
			<p class="subheading">Lenses</p>
			<p>1 35mm - T2.5 Square Front<br />
			1 50mm – T2.5 Round Front<br />
			1 80mm – T2.5 Square Front</p>
		</div>
	</div><!-- .lenses -->
	
	<div class="accessories equip-content">
		<h1>Accessories</h1>
		<div class="half-column">
			<h2>Accessories</h2>
			<p>1 Arri FF-4 Duel Follow Focus Set for 15mm/19mm Rods<br />
			1 Arri FF-4 15" Whip and Speed Crank <br />
			1 Arri MB-20 II 15mm/19mm 3-Stage Mattebox Kit / 3 4x5.6 / 1 Top Flag<br />
			1 Chrosziel MB-450-02 15mm 2-Stage LW Mattebox / 1 4x4 Stage / 1 4x5.6 Stage  <br />
			1 Sony ENG Quick Release Plate <br />
			1 Ronford Baker 15mm/19mm Duel Hand Grips<br />
			1 Arri ALEXA Ombre Rain Cover</p>
			<h2>Tripod</h2>
			<p>1 Sachtler CF-100ENG HD 2CF Carbon Fiber HD Tripod Legs / 1 Ground Spreaders<br />
			1 100mm Sachtler 20P Tripod Head<br />
			1 100mm Hi-Hat</p>
		</div>
		<div class="half-column last">
			<h2>Monitor</h2>
			<p>1 Sony OLED PVM-1741 17" Monitor<br />
			1 17" Acrylic Protection Screen Panel for Sony OLED PVM-1741<br />
			1 Sony OLED PVM-1741 Table Top Platform<br />
			1 Monitor Hoodman<br />
			1 Monitor Bracket and Stand Stud (C-Stand/Roller Stand Mount)<br />
			1 Anton Bauer Battery Adapter<br />
			1 50' BNC Cable / 1 100' BNC Cable</p>
		</div>
	</div><!-- .lenses -->

</div><!-- #content-equipment -->

<div class="clear"></div>

<script type="text/javascript">
$(document).ready(function() {
	$('.submenu a').click(function(e){
		e.preventDefault();
		$('.equip-content').hide();
		$('.submenu a').removeClass('hit');
		$(this).addClass('hit');
	});
	$('a.camera').click(function(e){
		$('.camera.equip-content').show();
	});
	$('a.lenses').click(function(e){
		$('.lenses.equip-content').show();
	});
	$('a.accessories').click(function(e){
		$('.accessories.equip-content').show();
	});
});
</script>
