<div id="content-work" class="content">

	<h1>Works</h1>
	<p class="subheading">Recognition / Accomplishments</p>
	
	<div class="work-column">
		<h2>Feature</h2>
		<p><strong>Hugo</strong><br />
		Martin Scorsese/Robert Richardson</p>
		<p><strong>Skyfall	</strong><br />
		Director/Producer</p>
		<p><strong>The Avengers</strong><br />
		Director/Producer</p>
		<p><strong>Drive</strong><br />
		Director/Producer</p>
		<p><strong>Anonymous</strong><br />
		Director/Producer</p>
		<p><strong>Prom</strong><br />
		Director/Producer</p>
		<p><strong>Melancholia</strong><br />
		Director/Producer</p>
		<p><strong>Torchwood: Miracle Day</strong><br />
		Director/Producer</p>
	</div>
	
	<div class="work-column last">
		<h2>Television</h2>
		<p><strong>Hugo</strong><br />
		Martin Scorsese/Robert Richardson</p>
		<p><strong>Skyfall	</strong><br />
		Director/Producer</p>
		<p><strong>The Avengers</strong><br />
		Director/Producer</p>
		<p><strong>Drive</strong><br />
		Director/Producer</p>
		<p><strong>Anonymous</strong><br />
		Director/Producer</p>
		<p><strong>Prom</strong><br />
		Director/Producer</p>
		<p><strong>Melancholia</strong><br />
		Director/Producer</p>
		<p><strong>Torchwood: Miracle Day</strong><br />
		Director/Producer</p>
	</div>
	
	<div id="work-video">
		<iframe src="http://player.vimeo.com/video/22439234" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
	</div>
	
	<div class="clear"></div>

</div><!-- #content-contact -->

<div class="clear"></div>
