<div id="content-work" class="content">

	<h1>ALEXA Plus</h1>
	<p class="subheading">Camera</p>
	
	<div id="camera-left">
		<p style="margin-top:0">The ARRI ALEXA PLUS digital camera system is leading the field in digital acquisition as one of the best capture options for cinematography and filmmaking today. Throughout its 90-year history, ARRI has been a groundbreaker in the field of revolutionary design and engineering of cameras for motion picture 16mm, 35mm, and 65mm film. ARRI's legacy of German engineering has brought a new front to digital camera technology today with the ALEXA PLUS. The ALEXA PLUS system promises a high quality, film-like image with a low noise floor, wide dynamic range, and an edit friendly workflow. As a tool of the modern age it is highly regarded as the closest image to motion picture film ever produced by emerging and master cinematographers.</p>
		<p><strong>Technical Specs:</strong><br />
		<span class="small-text">- 14 Stops of exposure latitude<br>
			- 800 ISO base sensitivity<br>
			- In-camera recording  to SxS Pro Cards / Log- C / Rec 709 / 2048 x 1152 2K / 1920 x 1080 HD<br>
			- Apple ProRes 422 / (Proxy) / (LT) / (HQ) / Apple ProRes 4444<br>
			- Off-board recording / ARRIRAW  / 2048 x 1152 2K  <br>
			- High speed license 0.75-120 fps<br>
			- Anamorphic de-squeeze features<br>
			- 16:9 Sensor <br>
			- Lightweight design / 13.7 lbs / 6.2 kg<br>
			- For more info visit: <a href="http://www.arridigital.com" target="_blank">www.arridigital.com</a></span></p>
	</div>
	
	<div class="gallery">
		<div class="feature"><img src="/img/cameras/alexa-plus/cam1.jpg" alt="" /></div>
		<ul>
			<li class="active"><a href="#" title=""><img data-img="/img/cameras/alexa-plus/cam1.jpg" src="/img/cameras/alexa-plus/camsmll1.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/alexa-plus/cam2.jpg" src="/img/cameras/alexa-plus/camsmll2.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/alexa-plus/cam3.jpg" src="/img/cameras/alexa-plus/camsmll3.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/alexa-plus/cam4.jpg" src="/img/cameras/alexa-plus/camsmll4.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/alexa-plus/cam5.jpg" src="/img/cameras/alexa-plus/camsmll5.jpg" alt="" /></a><div class="white-hover"></div></li>
		</ul>
	</div>
	
	<div class="clear"></div>

</div><!-- #content-contact -->

<div class="clear"></div>

<script>
	$('.gallery ul li img').click( function(e){
		$this = $(this);

		p_active = $('.gallery ul li.active').removeClass('active');
		$this.parent().parent().addClass('active');
		
		$('.gallery .feature img').attr('src', $this.attr('data-img') );
	});
</script>
