<div id="content-work" class="content">

	<h1>Sony PMW-F5</h1>
	<p class="subheading">Camera</p>
	
	<div id="camera-left">
		<p style="margin-top:0">The Sony PMW-F5 is a camera engineered with all cinematography needs in mind.  The 4K CMOS imaging sensor in the PMW-F5 features 8.9 megapixels and records a super sampled HD and 2K image while preparing you for the 4K future. The F5's imaging power is further bolstered by exceptional exposure latitude; rated at 14 stops of dynamic range. With planned firmware updates that include higher frame rates, more operating features and more recording options to come the PMW-F5 is an advanced digital acquisition tool for cinematographers of today and tomorrow. </p>
		<p><strong>Technical Specs:</strong><br />
		<span class="small-text">- 14 stops of exposure latitude<br>
			- 2000 ISO base sensitivity<br>
			- 8.9MP Super 35mm 4K CMOS Image Sensor<br>
			- In-camera recording to SxS Pro Cards /  2048 x 1152 2K / 1920 x 1080 HD<br>
			- MPEG2 8bit 4:2:2 / XAVC 10bit 4:2:2 / SR Codec 12bit 4:4:4<br>
			-  Off-board recording / RAW  / 2048 x 1152 2K  / 4K <br>
			- High speed firmware 1-120 fps<br>
			- Highly Modular Design <br>
			- Native FZ-MOUNT and PL-MOUNT<br>
			- Built-in ND filters<br>
			- SONY OLED DVF-EL100 Viewfinder<br>
			- Sony BP-FL75 Olivine battery technology
			</span></p>
	</div>
	
	<div class="gallery">
		<div class="feature"><img src="/img/cameras/sony-pmwf5/1.jpg" alt="" /></div>
		<ul>
			<li class="active"><a href="#" title=""><img data-img="/img/cameras/sony-pmwf5/1.jpg" src="/img/cameras/sony-pmwf5/1-th.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/sony-pmwf5/2.jpg" src="/img/cameras/sony-pmwf5/2-th.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/sony-pmwf5/3.jpg" src="/img/cameras/sony-pmwf5/3-th.jpg" alt="" /></a><div class="white-hover"></div></li>
			<li><a href="#" title=""><img data-img="/img/cameras/sony-pmwf5/4.jpg" src="/img/cameras/sony-pmwf5/4-th.jpg" alt="" /></a><div class="white-hover"></div></li>
		</ul>
	</div>
	
	<div class="clear"></div>

</div><!-- #content-contact -->

<div class="clear"></div>

<script>
	$('.gallery ul li img').click( function(e){
		$this = $(this);

		p_active = $('.gallery ul li.active').removeClass('active');
		$this.parent().parent().addClass('active');
		
		$('.gallery .feature img').attr('src', $this.attr('data-img') );
	});
</script>
