<div id="content-equipment" class="content">

	<ul class="submenu">
		<li><a href="#" class="accessories"></a></li>
		<li><a href="#" class="lenses"></a></li>
		<li><a href="#" class="camera"></a></li>
		<li><a href="#" class="support"></a></li>
		<li><a href="#" class="lighting"></a></li>
		<li><a href="#" class="monitors"></a></li>
	</ul>

	<div class="camera equip-content">
		<h1>Camera</h1>
		<p class="subheading">Camera Rentals</p>

		<h2>ALEXA plus</h2>
		<p class="subheading">Camera</p>
	
		<div class="half-column">
			<p>1 Arri ALEXA Plus Digital Cinema Camera<br>
			Arri High Speed License 120FPS /<br>
			Arri Anamorphic De-Squeeze License / 2k Firmware<br>
			1 Arri ALEXA EVF-1 Electronic Viewfinder<br>
			1 Arri ALEXA VMB-2 Viewfinder Mounting Bracket<br>
			1 Arri ALEXA Viewfinder Extension Bracket<br>
			1 Arri ALEXA Viewfinder Cable Short (0.35mm/1.2ft) KC 150-s<br>
			1 Arri ALEXA Viewfinder Cable Medium (0.65m/2.1ft) KC 151-S<br>
			1 Arri ALEXA Ethernet Cable (3.00m/9.8ft) KC 153-S<br>
			1 Arri XLR Sound Adapter Cable <br>
			1 Arri ALEXA 12V Accessory Cable<br>
			1 Arri BPA-1 Bridge Plate Adapter for ALEXA<br>
			1 Arri WA-1 Wedge Adapter for ALEXA<br>
			1 Arri LB-1 Leveling Block for ALEXA<br>
			1 Arri BP-12 Bridge Plate Set (19mm)<br>
			1 12" Dovetail Plate <br>
			1 Arri SP-3 Shoulder Pad for ALEXA<br>
			1 Arri CCH-1 Center Camera Handle for ALEXA<br>
			1 Arri ALEXA PL Port Cap<br>
			1 Arri HEB-2 Handle Extension Block for ALEXA<br>
			1 Arri ALEXA Anton Bauer Battery Adapter Back for Gold Mount<br>
			1 Arri ALEXA SD Card, 4GB</p>
		</div>
		<div class="half-column last">
			<h3>On-Board Monitor</h3>
			<p>1 TV Logic 5.6" - Full Version Multi-format HD/SD/HDM 3G Viewfinder Monitor<br>
				1 TV Logic Panasonic Battery Mount, 2 Panasonic Batteries, and 1 Panasonic Charger<br>
				1 TV Logic D-Tap Power Cable for the VFM-056WP Monitor<br>
				1 TV Logic External Protection Screen Panel for VFM-056W / 1 5.6" Hoodman<br>
				1 Cine Arm – Medium<br>
				1 12" BNC Cable<br>
				1 Anton Bauer Sandwich Adapter with 4 Powertap Connectors</p>
			
			<h3>Media</h3>
			<p>4 Sony PRO SxS Memory Cards 64GB<br>
				1 Sony Card Reader / 1 USB Cable / 1 AC Power Adapter<br>
				1 Echo SXS Express Card Thunderbolt Adapter Pro<br>
				1 Thunderbolt to Thunderbolt Cable</p>

			<h3>Batteries</h3> 
			<p>6 Anton Bauer Hytron 140w 14.4Vv NiMH Battery<br>
				1 Anton Bauer TM4 4-Position Simultaneous Fast Charger<br>
				1 Arri 24V 10ft. 3-Pin Power Cable for ALEXA<br>
				1 Arri 221W/24v Power Supply<br>
				2 Power Cables<br>
				1 Anton Bauer Cine VCLXCA Block Battery Pack - 30 Volt Output Option <br>
				1 Anton Bauer Cine VCLXCA Charger / 1 Charging Cable</p>
		</div>
	
		<div class="clear"></div>

		<h2>Sony PMW-F5</h2>
		<p class="subheading">Camera</p>
	
		<div class="half-column">
			<p>1 Sony PMW-F5 Camera Body<br>
				1 Sony DVF-EL100 OLED Viewfinder <br>
				1 Arri VFA1 Viewfinder Adapter <br>
				1 Viewfinder Cable <br>
				1 Arri Adapter Plate <br>
				1 Arri Shoulder Pad <br>
				1 Arri Top handle <br>
				1 Arri CCH-2 Center Camera Handle <br>
				1 Wooden Camera 19mm Bridge Plate Set (19mm)<br>
				1 12" Dovetail Plate</p>

			<h3>Media</h3>
			<p>2 Sony Pro SXS Memory Cards 128GB<br>
				1 Sony Card Reader / 1 USB Cable / 1 AC Power Adapter<br>
				1 Echo SXS Express Card Thunderbolt Adapter Pro<br>
				1 Thunderbolt to Thunderbolt Cable</p>
		</div>
		<div class="half-column last">
			<h3>SONY PMW-­F5 Accessories Kit</h3>
			<p>1 Arri MMB-1 Matte Box Kit<br>
				1 Arri MMB-1 Top Flag <br>
				2 Arri 19mm Support Rods Steel 13.6"<br>
				2 Arri 15mm Support Rods Steel  240mm<br>
				1 Arri FF-4 Follow Focus <br>
				1 Small HD AC7 LCF Monitor w/ SDI Input  /<br>
				1 Small HD Hoodman<br>
				4 Panasonic Batteries,and 2 Panasonic Charger<br>
				1 3' BNC Cable <br>
				1 NOGA 6" Articulating Cine Arm </p>

			<h3>Batteries</h3>
				<p>2 Sony BPFL75 Olivine VMount Batteries <br>
				1 Sony BC­L90 Battery Charger <br>
				1 Power Cable</p>
		</div>
	
		<div class="clear"></div>

		<h2>5D Mark III</h2>
		<p class="subheading">Camera</p>
	
		<div class="half-column">
			<p>1 Canon 5D Mark III Digital Camera<br>
				1 Canon EF 16-35mm II f/2.8 L-Series <br>
				1 Canon EF 24-105mm f/4.0 L-Series <br>
				4 Canon Batteries <br>
				4 SanDisk 32GB Extreme CF Cards 90MB/S<br>
				1 Canon Charger / 1 Canon AC Power Adapter<br>
				1 Redrock Micro DSLR Shoulder Rig / Hand Grips Kit</p>
		</div>
		<div class="half-column last">
			<h3 style="margin-top:-4em">additional equipment available upon request</h3>
		</div>
	
		<div class="clear"></div>
	
	</div><!-- .camera -->
	
	<div class="lenses equip-content">
		<h1>Lenses</h1>
		<p class="subheading">Available for rent</p>
		<div class="half-column">
			<h2>Zeiss CP.2</h2>
			<p class="subheading">Lenses</p>
			<p>1 Zeiss Compact Prime Lenses (PL/EF Mount)<br />
			1 Zeiss Transport Case for CP.2 System / Torque Wrench / Siemens Test Chart<br />
			21mm – T2.9<br />
			28mm – T2.1<br />
			35mm – T2.1<br />
			50mm – T2.1<br />
			85mm – T2.1<br /><br /><br /><br /></p>
			<h3>additional equipment available upon request</h3>
		</div>
		<div class="half-column last">
			<h2>LOMO Anamorphic</h2>
			<p class="subheading">Lenses</p>
			<p>1 35mm - T2.5 Square Front<br />
			1 50mm – T2.5 Round Front<br />
			1 80mm – T2.5 Square Front</p>
		</div>
	</div><!-- .lenses -->
	
	<div class="accessories equip-content">
		<h1>Accessories</h1>
		<div class="half-column">
			<h2>Matte Box</h2>
			<p>1 Arri MB-20 II 15mm/19mm 3-Stage Matte Box Kit / 114mm Dia. Filter Ring / (3) 4x5.65" Stages <br>
				1 Arri MB-20 II Top Flag<br>
				1 Arri LMB-15 3-Stage Clip-On Matte Box Kit / 143mm / 114mm / 95mm Clamping Rings / (3) 4x5.65" Stages <br>
				1 Arri LMB-15 Top Flag<br>
				1 Chrosziel MB-450-02 15mm 2-Stage LW Matte Box /114mm Dia. Ring / (1) 4x4" Stage / (1) 4x5.65" Stage</p>
			<h2>Follow Focus</h2>
			<p>1 Arri FF-4 Dual Wheel Follow Focus Set for 15mm/19mm Rods<br>
				1 Arri FF-4 15" Whip<br>
				1 Arri Speed Crank</p>
			<h2>Filters</h2>
			<p>1 Schneider 4x5.65" IR ND .3 / .6  / .9 / 1.2<br>
				1 Schneider 4x5.65" Circ Pola<br>
				1 Schneider 4x5.65" Optical Flat Clear <br>
				1 Tiffen 4x5.6 BPM  1/8 - 1/4 - 1/2 - 1 </p>
			<h2>Accessories</h2>
			<p>1 Ronford Baker 15mm/19mm Dual Hand Grips<br>
				1 Arri ALEXA Ombre Rain Cover <br>
				2 Arri 19mm Support Rods Steel 13.6"<br>
				2 Chrosziel 15mm Support Rods Steel 12"<br>
				1 Sony ENG Quick Release Plate (For ALEXA)<br>
				1 MAGLINER Gemini Jr. Hand Truck with Folding Nose and Top Shelf</p>
		</div>
	</div><!-- .lenses -->

	<div class="lighting equip-content">
		<h1>Lighting</h1>
		<p class="subheading"></p>
		<div class="half-column">
			<h2>Lighting</h2>
			<p><br><br>1 Joker Bug 400 K5600 Light Kit with Flicker Free Ballast, Lens Kit, Scrims, Barn Door, Chimera Speed Ring<br>
			1 Chimera Video Pro, Medium <br>
			1 Chimera Video Pro, XS <br>
			1 Matthews 3-Rise Beefy Baby 750 Stands with Rocky Mountain Legs<br><br><br><br></p>
			<h3>additional equipment available upon request</h3>
		</div>
	</div><!--.monitors-->

	<div class="monitors equip-content">
		<h1>Monitors</h1>
		<p class="subheading">Available for rent</p>
		<div class="half-column">
			<h2>Sony OLED PVM-1741 Monitor 17"</h2>
			<p><br><br>1 Sony OLED PVM-1741 17" Monitor<br>
				1 17" Acrylic Protection Screen Panel for Sony OLED PVM-1741<br>
				1 Sony OLED PVM-1741 Table Top Platform<br>
				1 Monitor Hoodman<br>
				1 Monitor Bracket and Stand Stud (C-Stand/Roller Stand Mount)<br>
				1 Anton Bauer Battery Adapter<br>
				1 10' 4-Pin XLR Male to 4-Pin XLR Female<br>
				1 50' BNC Cable<br>
				1 100' BNC Cable<br><br><br><br><br><br></p>
			<h3>additional equipment available upon request</h3>
		</div>
		<div class="half-column last">
			<h2>TV Logic Monitor with Waveform/Vectorscope 5.6"</h2>
			<p><br><br>1 TV Logic 5.6" - Full Version Multi-format HD/SD/HDM 3G Viewfinder Monitor<br>
				1 TV Logic Panasonic Battery Mount, 2 Panasonic Batteries, and 1 Panasonic Charger<br>
				1 TV Logic D-Tap Power Cable for the VFM-056WP Monitor<br>
				1 TV Logic External Protection Screen Panel for VFM-056W / 1 5.6" Hoodman<br>
				1 Cine Arm – Medium<br>
				1 12" BNC Cable</p>
		</div>
	</div><!--.monitors-->

	<div class="support equip-content">
		<h1>Support</h1>
		<p class="subheading">Available for rent</p>
		<div class="half-column">
			<h2>O’Connor 2575D Kit</h2>
			<p><br><br>1 O'Connor 2575D Mitchel Head<br>
				1 O'Connor Eurostyle Quick Release Plate<br>
				1 O'Connor Handle &amp; Handle Extension<br>
				1 O'Connor Standard Legs / 1 Ground Spreader<br>
				1 O'Connor Baby Legs / 1 Ground Spreader<br>
				1 Ronford Mitchell High-Hat w/ Base</p>
			<h2>Sachtler 20P Kit</h2>
			<p><br><br>1 100mm Sachtler 20P Tripod Head<br>
				1 Sachtler CF-100ENG HD 2CF Carbon Fiber HD Tripod Legs / 1 Ground Spreaders<br>
				1 100mm Hi-Hat<br><br><br><br></p>
			<h3>additional equipment available upon request</h3>
		</div>
	</div><!--.monitors-->

</div><!-- #content-equipment -->

<div class="clear"></div>

<script type="text/javascript">
$(document).ready(function() {

	var hash = window.location.hash;
	hash != '' ? hash = hash.substring(1) : hash = 'camera';
	$('.'+hash).addClass('hit');
	$('.'+hash+'.equip-content').show();

	$('.submenu a, #main-nav-equipment li a').click(function(e){
		e.preventDefault();
		$('.equip-content').hide();
		$('.submenu a').removeClass('hit');
		$(this).addClass('hit');
	});
	$('a.camera').click(function(e){
		$('.camera.equip-content').show();
	});
	$('a.lenses').click(function(e){
		$('.lenses.equip-content').show();
	});
	$('a.accessories').click(function(e){
		$('.accessories.equip-content').show();
	});
	$('a.support').click(function(e){
		$('.support.equip-content').show();
	});
	$('a.lighting').click(function(e){
		$('.lighting.equip-content').show();
	});
	$('a.monitors').click(function(e){
		$('.monitors.equip-content').show();
	});
});
</script>
